# Generated by Django 2.2.5 on 2019-09-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Banknote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Ruble'), ('USD', 'US dollar'), ('EUR', 'EURO')], default='Ruble', max_length=3)),
                ('value', models.PositiveSmallIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Atm')),
            ],
            options={
                'ordering': ['currency', '-value'],
                'unique_together': {('currency', 'value')},
            },
        ),
    ]
